export const cartItemsMock = [
  {
    id: 1,
    quantity: 1,
    total_price: 10.99,
    brand: 'Mock brand 1',
    category: 'Mock category 1',
    name: 'Mock name 1',
    price: 10,
    size: '10ml',
    details: 'Mock details 1',
    usage: 'Mock',
    ingredients: 'Mock ingredients list',
  },
  {
    id: 1,
    quantity: 2,
    total_price: 11.0,
    brand: 'Mock brand 2',
    category: 'Mock category 2',
    name: 'Mock name 2',
    price: 20,
    size: '20ml',
    details: 'Mock details 2',
    usage: 'Mock',
    ingredients: 'Mock ingredients list',
  },
];
