name: Jest Automatic Testing

on: pull_request

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    env:
      VITE_DATABASE_URL: ${{ secrets.VITE_DATABASE_URL }}
      VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install all dependencies
        run: npm install

      - name: Run Jest Tests with Firebase config
        run: |
          export VITE_DATABASE_URL=$VITE_DATABASE_URL
          export VITE_PROJECT_ID=$VITE_PROJECT_ID
          npm run test
